name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Julia 1.5
        uses: actions/setup-julia@v1
        with:
          julia-version: 1
          julia-arch: x64
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.develop(PackageSpec(path=pwd()))'
      - name: Test
        run: julia --project=. --sysimage-native=./sys.so main.jl
